server:
  port: 8764

spring:
  application:
    name: server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/admin?serverTimezone=GMT%2B8&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 111111
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 1000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
