eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: zuul
zuul:
  routes:
    user:
      path: /client-user/**
      serviceId: client
    test:
      path: /client-test/**
      serviceId: client-test

