server:
  port: 8762

spring:
  application:
    name: client
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 1000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/admin?serverTimezone=GMT%2B8&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 111111


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/





